server:
  port: ${SERVER_PORT:8057}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:article}
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK:http://localhost:9090/realms/graduation}
  r2dbc:
    url: ${DATASOURCE_R2DBC_URL:r2dbc:postgresql://localhost:5432/rag?currentSchema=article_service}
    username: ${DATASOURCE_NAME:rag_user}
    password: ${DATASOURCE_PASSWORD:rag_pass}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    connection-timeout: ${RABBITMQ_CON_TIMEOUT:5000}

app:
  article:
    flyway:
      base-line-on-migrate: true
      data-source-url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/rag}
      user: ${DATASOURCE_NAME:rag_user}
      password: ${DATASOURCE_PASSWORD:rag_pass}
      schemas: ${DATASOURCE_SCHEMAS:article_service}
      locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    rabbit:
      exchange: "article.exchange"
      routing-key: "article.outbox"
      queue: "article.outbox.queue"
    scheduler:
      cron: "0/30 * * * * ?"
      batch-size: 10
      enabled: true
    max-attempts: 3
    retry-delay: 5000

management:
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: readinessState
  endpoints:
    web:
      exposure:
        include: health,info,flyway

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n"
  level:
    root: INFO
#    org.springframework.data.r2dbc: DEBUG
#    io.r2dbc.postgresql.QUERY: DEBUG
#    io.r2dbc.postgresql.PARAM: TRACE